#:kivy 1.10.0

<CodeBlock>:
    selected: False
    name: "Block 1"
    default_width: 2
    default_height: 1
    default_size: self.default_width, self.default_height
    scale_factor: 100
    size: self.default_width * self.scale_factor, self.default_height * self.scale_factor
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        pos: root.pos
        size: root.size
        color: [0, 0, 0, 1]
        text: root.name
